# This code does not work not because of an error in Python or in this file.
# The problem lies with X (Twitter) and the twikit library.
#
# - The client.login() method in twikit attempts to replicate the login process in X.
# - X uses a complex protection mechanism (anti-bot)
# - During login, X expects a special temporary token (ATT),
#   which is usually generated by JavaScript in the browser.
# - twikit cannot correctly generate or reproduce this token
#
# X returns an error:
# "Invalid ATT for the flow"
#
# A simpler approach:
# - Do not use client.login()
# - Log in to X via your browser
# - Save cookies from browser in python-twikit/cookies.json
#   (see python-twikit/cookies.example.json)
#
# Conclusion:
# The code is correct, but blocked by X protection.
# This is a platform limitation.
#
# ------------------------------------------------------------


import asyncio
from dotenv import load_dotenv
import os
from twikit import Client

load_dotenv()

async def main():
    client = Client(language="en-US")
    await client.login(
        auth_info_1=os.getenv("USERNAME"),
        auth_info_2=os.getenv("EMAIL"),
        password=os.getenv("PASSWORD"),
    )
    
    client.save_cookies("cookies.json")

asyncio.run(main())
